### ISSUE TITLE
ModuleNotFoundError: No module named 'apogee.models.discrete'

### ISSUE THREAD

**Issue by tobimichigan** [markdouthwaite/apogee#5]
Hi Developers @ Apogee. Please I tried running your example from jupyter notebook after running pip install . / pip install -r requirements and it gave:

"ModuleNotFoundError: No module named 'apogee.models.discrete"

Any clues?

**Comment by markdouthwaite** [comment]
Hey! 

Thanks for raising this issue. You're right to raise this, the `master` branch is a little out of sync and needs fixing. 

In the meantime, try checking out the `v0.2.0` branch -- it's more up to date.

If you need an example of doing something specific let me know! 🙂 

There will be quite a bit of work on `apogee` in the new year too, so stay posted!

**Comment by markdouthwaite** [comment]
I'm going to close this. Let me know if you have any further issues.
